# Generated by Django 6.1.2 on 2026-10-06 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelstation',
            name='retail_price',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
    ]
