"""
Django settings for spotfleet project.

Generated by 'django-admin startproject' using Django 6.1.2.
"""

from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

# Take-home demo: development-friendly defaults. No secrets are used anywhere
# in this project -- every external service is free and key-less.
SECRET_KEY = 'django-insecure-z73wjqe!%t&_jfnngdqau85o=fncox4v5nock-3=r0k^0h!gj!'
DEBUG = True
ALLOWED_HOSTS = ['*']

INSTALLED_APPS = [
    'django.contrib.staticfiles',
    'fuel',
]

MIDDLEWARE = [
    'django.middleware.common.CommonMiddleware',
]

ROOT_URLCONF = 'spotfleet.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
            ],
        },
    },
]

WSGI_APPLICATION = 'spotfleet.wsgi.application'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        # runserver is threaded; let concurrent cache writes wait on each
        # other instead of failing with "database is locked".
        'OPTIONS': {'timeout': 20},
    }
}

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

STATIC_URL = 'static/'
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ---------------------------------------------------------------------------
# Spot Fleet: fuel-optimized routing configuration
#
# Everything below is free / open data. No API keys are required:
#   * Routing    -> OSRM public demo server (OpenStreetMap data)
#   * Geocoding  -> Photon (komoot) with Nominatim as fallback
#   * Map tiles  -> OpenStreetMap tiles rendered on Leaflet
# ---------------------------------------------------------------------------

# Vehicle model
VEHICLE_RANGE_MILES = 500   # maximum range on a full tank
VEHICLE_MPG = 10            # fuel economy

# Truckstops within this distance of the route polyline are considered.
CORRIDOR_BUFFER_MILES = 4.0

# The full OSRM polyline is thinned to roughly this spacing before it is used
# for corridor matching and drawing. Half a mile keeps the line on the road
# while keeping payloads and projection cost small.
ROUTE_MIN_SPACING_MILES = 0.5

# Cheap first-pass screening radius (miles) before exact projection.
CORRIDOR_SCREEN_MILES = 20.0

# Assumption: the truck departs with a full (already paid for) tank, so fuel
# purchased before departure is not part of the trip cost.
START_WITH_FULL_TANK = True

# External services
OSRM_BASE_URL = 'https://router.project-osrm.org'
PHOTON_BASE_URL = 'https://photon.komoot.io/api'
NOMINATIM_BASE_URL = 'https://nominatim.openstreetmap.org'
HTTP_USER_AGENT = 'spot-fleet-takehome/1.0 (fuel-optimized route planner)'

# Polite rate limits for the free geocoders (requests per second). Photon is
# used for the bulk one-time seeding of truckstop coordinates; Nominatim is
# kept at its documented 1 req/s ceiling.
PHOTON_QPS = 4.0
NOMINATIM_QPS = 1.0

# Derived data snapshot written after seeding so a fresh clone can be
# populated instantly without re-geocoding.
GEOCODED_SNAPSHOT_PATH = BASE_DIR / 'data' / 'stations_geocoded.json'
